version: '3.9'

services:
  database:
    image: mysql:latest
    container_name: db
    env_file:
      ./.env.db.example
    ports:
      - "3306:3306"
    restart:
        unless-stopped
    volumes:
      - ./db.vol/db/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.example
      - ./.env.db.example
    expose:
      - 8000
    ports:
      - 9008:8000
    depends_on: 
      - database
    volumes:
      - ./logs:/code/src/logs
    