version: '3.9'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: db
    env_file:
      ./.env.db
    ports:
      - "3306:3306"
    restart:
        unless-stopped
    #volumes:
    #  - ./db.vol/db.conf:/etc/mysql/conf.d
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./.env.db
    expose:
      - 8000
    ports:
      - 9008:8000
    depends_on: 
      - database
    volumes:
      - ./logs:/code/src/logs
    